/* Exam Admin Intelligence Portal — HTML/CSS/JS only */
let DATA={exams:[],results:[],students:[],questions:[],meta:{sources:0,failedSources:0,failed:[]}};
let currentPage='dashboard';
let LIVE_MODE=false, API_LOADING=false;
let selectedExamId=localStorage.getItem('selectedExamId')||'ALL';
let searchTerm='', resultStatus='ALL', studentSearch='';
let examSources=[];
try{examSources=JSON.parse(localStorage.getItem('examSources')||'[]')}catch(e){examSources=[]}
if(!examSources.length){const u=(localStorage.getItem('examApiUrl')||'').trim();if(u)examSources=[{id:'EXAM-1',name:'Computer Science Online Examination',code:'CS-EXAM',url:u,active:true,expectedStatus:'AUTO'}]}
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=r=>Number((Number(r.percentage??((Number(r.score)||0)/(Number(r.total)||1)*100))).toFixed(1));
function saveSources(){localStorage.setItem('examSources',JSON.stringify(examSources)); const first=examSources.find(x=>x.url); if(first)localStorage.setItem('examApiUrl',first.url); else localStorage.removeItem('examApiUrl')}
function audit(action,detail=''){let a=[];try{a=JSON.parse(localStorage.getItem('auditLog')||'[]')}catch(e){} a.unshift({time:new Date().toISOString(),action,detail});localStorage.setItem('auditLog',JSON.stringify(a.slice(0,200)))}
function filteredResults(){let r=selectedExamId==='ALL'?DATA.results:DATA.results.filter(x=>String(x.examId)===String(selectedExamId)); if(searchTerm)r=r.filter(x=>[x.student,x.email,x.roll,x.exam].join(' ').toLowerCase().includes(searchTerm.toLowerCase())); if(resultStatus!=='ALL')r=r.filter(x=>x.status===resultStatus); return r}
function filteredExams(){return selectedExamId==='ALL'?DATA.exams:DATA.exams.filter(e=>String(e.id)===String(selectedExamId))}
function studentsFrom(rows){const m={};rows.forEach(r=>{const k=r.email||r.roll||r.student||r.id;if(!m[k])m[k]={name:r.student||r.email,roll:r.roll,email:r.email,className:r.classDepartment||'',attempts:0,results:[]};m[k].attempts++;m[k].results.push(r)});return Object.values(m)}
function filteredStudents(){let a=studentsFrom(selectedExamId==='ALL'?DATA.results:DATA.results.filter(r=>String(r.examId)===String(selectedExamId))); if(studentSearch)a=a.filter(s=>[s.name,s.roll,s.email,s.className].join(' ').toLowerCase().includes(studentSearch.toLowerCase())); return a}
function normaliseLive(payload,source){
 if(!payload||payload.success!==true)throw new Error(payload?.error||'API returned success=false');
 const ei=payload.exam||{}, rows=Array.isArray(payload.results)?payload.results:[], total=Number(ei.totalMarks||source.totalMarks||10), passing=Number(ei.passingMarks||source.passingMarks||Math.ceil(total/2)), sourceId=source.id, examName=String(ei.name||source.name||'Untitled Exam');
 const results=rows.map((r,i)=>{const score=Number(r.score)||0;return {id:String(r.id||`${sourceId}-RES-${i+1}`),student:String(r.student||r.name||r.email||''),roll:String(r.rollNumber??r.roll??''),email:String(r.email||''),exam:examName,examId:sourceId,score,total:Number(r.total||total),percentage:Number(r.percentage??(score/(Number(r.total||total)||1)*100)),status:String(r.status||((score>=passing)?'PASS':'FAIL')),submitted:String(r.submitted||''),mobile:String(r.mobile??''),classDepartment:String(r.classDepartment??''),questions:Array.isArray(r.questions)?r.questions:[]}});
 const submitted=results.length, pass=results.filter(r=>r.status==='PASS').length, avg=submitted?results.reduce((a,r)=>a+pct(r),0)/submitted:0;
 const exam={id:sourceId,name:examName,code:String(source.code||ei.code||sourceId),date:results[0]?.submitted?new Date(results[0].submitted).toLocaleDateString():new Date().toLocaleDateString(),students:Number(payload.statistics?.totalStudents??submitted),submitted,avg:Number(avg.toFixed(1)),status:source.active===false?'PAUSED':(source.expectedStatus&&source.expectedStatus!=='AUTO'?source.expectedStatus:'ACTIVE'),total,passing,duration:Number(ei.durationMinutes||source.duration||60)};
 const qmap={}; results.forEach(r=>r.questions.forEach(q=>{const k=q.question||q.q||q.h||`Question ${q.number||1}`;if(!qmap[k])qmap[k]={q:k,responses:0,answered:0};qmap[k].responses++;if(String(q.answer??q.v??'').trim())qmap[k].answered++}));
 return {exam,results,questions:Object.values(qmap),statistics:payload.statistics||{}};
}
async function fetchSource(s){const res=await fetch(s.url,{cache:'no-store',redirect:'follow'});if(!res.ok)throw new Error(`${s.name||s.id}: HTTP ${res.status}`);return normaliseLive(await res.json(),s)}
async function loadAllLiveData(silent=false){
 if(!examSources.length)throw new Error('No exam API sources configured. Add an exam in Settings.'); API_LOADING=true; const started=Date.now();
 try{const active=examSources.filter(s=>s.active!==false&&s.url);const settled=await Promise.all(active.map(async s=>{try{return {ok:true,data:await fetchSource(s),source:s}}catch(error){return {ok:false,error,source:s}}}));const good=settled.filter(x=>x.ok),bad=settled.filter(x=>!x.ok);if(!good.length)throw new Error(bad.map(x=>`${x.source.name}: ${x.error.message}`).join('\n'));
 const results=good.flatMap(x=>x.data.results), exams=good.map(x=>x.data.exam), q={};good.forEach(x=>x.data.questions.forEach(v=>{q[v.q]=(q[v.q]||{q:v.q,responses:0,answered:0});q[v.q].responses+=v.responses;q[v.q].answered+=v.answered}));DATA={exams,results,students:studentsFrom(results),questions:Object.values(q),meta:{sources:good.length,failedSources:bad.length,failed:bad.map(x=>x.source.name)}};LIVE_MODE=true;audit('SYNC',`${good.length} exam source(s), ${results.length} result(s)`);if(!silent){render();setUpdated(`Live • ${good.length} source${good.length===1?'':'s'} • ${((Date.now()-started)/1000).toFixed(1)}s`)}return {success:true,failed:bad}}finally{API_LOADING=false}}
async function refreshData(){if(examSources.length){try{await loadAllLiveData();return true}catch(e){setUpdated('API error');alert('Google API could not be loaded.\n\n'+e.message);return false}}render();setUpdated('Demo data refreshed');return false}
function setUpdated(t){if($('#lastUpdated'))$('#lastUpdated').textContent=t}
function statusBadge(s){return `<span class="status ${s==='PASS'||s==='ACTIVE'||s==='LIVE'?'pass':s==='FAIL'||s==='ERROR'?'fail':'pending'}">${esc(s)}</span>`}
function updateGlobalExamFilter(){const el=$('#globalExamFilter');if(!el)return;el.innerHTML='<option value="ALL">All Exams</option>'+DATA.exams.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('');if(!DATA.exams.some(e=>String(e.id)===String(selectedExamId)))selectedExamId='ALL';el.value=selectedExamId}
function render(){const titles={dashboard:['Dashboard','Exam performance overview'],exams:['Exams','Manage, monitor and configure examinations'],results:['Results','Search, filter and inspect submissions'],students:['Students 360°','Student directory, history and performance'],analytics:['Analytics','Performance and question response analysis'],comparison:['Exam Comparison','Compare examination metrics side-by-side'],reports:['Reports','Export, print and archive examination data'],settings:['Settings','Exam sources, health, audit and preferences']};$('#pageTitle').textContent=titles[currentPage][0];$('#pageSub').textContent=titles[currentPage][1];$('#content').innerHTML={dashboard,exams,results,students,analytics,comparison,reports,settings}[currentPage]();$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage));updateGlobalExamFilter();bindPage();}
function dashboard(){const rows=filteredResults(),ex=filteredExams(),students=studentsFrom(rows),avg=rows.length?rows.reduce((a,r)=>a+pct(r),0)/rows.length:0,pass=rows.filter(r=>r.status==='PASS').length,fail=rows.filter(r=>r.status==='FAIL').length,passRate=pass+fail?pass/(pass+fail)*100:0;const recent=[...rows].sort((a,b)=>new Date(b.submitted)-new Date(a.submitted)).slice(0,8);return `<div class="cards"><div class="card"><div class="metric-label">Exams</div><div class="metric">${ex.length}</div><div class="metric-foot">${selectedExamId==='ALL'?'All configured':'Selected'}</div></div><div class="card"><div class="metric-label">Unique Students</div><div class="metric">${students.length}</div><div class="metric-foot">Current filter</div></div><div class="card"><div class="metric-label">Submissions</div><div class="metric">${rows.length}</div><div class="metric-foot">Google Forms synced</div></div><div class="card"><div class="metric-label">Average</div><div class="metric">${avg.toFixed(1)}%</div><div class="metric-foot">Pass rate ${passRate.toFixed(1)}%</div></div></div><div class="grid2"><div class="page-card"><div class="section-title"><h2>Recent Submissions</h2><button class="btn" data-action="go-results">View all</button></div><div class="table-wrap">${resultTable(recent,false)}</div></div><div class="page-card"><div class="section-title"><h2>Exam Health</h2><span class="muted">Source status</span></div>${ex.length?ex.map(e=>`<div class="health-row"><div><b>${esc(e.name)}</b><small>${esc(e.code)} • ${e.submitted}/${e.students||e.submitted} submitted</small></div>${statusBadge(e.status)}</div>`).join(''):'<div class="empty">No exams loaded.</div>'}</div></div><div class="grid2"><div class="page-card"><div class="section-title"><h2>Performance Distribution</h2><span class="muted">Current results</span></div><div class="bar-row"><span>Pass</span><div class="bar"><i style="width:${passRate}%"></i></div><b>${pass}</b></div><div class="bar-row"><span>Fail</span><div class="bar"><i style="width:${100-passRate}%"></i></div><b>${fail}</b></div></div><div class="page-card"><div class="section-title"><h2>Quick Actions</h2></div><div class="quick-grid"><button class="quick" data-action="go-reports">Export Reports</button><button class="quick" data-action="go-students">Student 360°</button><button class="quick" data-action="go-analytics">Question Analytics</button><button class="quick" data-action="go-settings">API Health</button></div></div></div>`}
function resultTable(rows,actions=true){if(!rows.length)return '<div class="empty">No results match the current filters.</div>';return `<table class="table"><thead><tr><th>Student</th><th>Exam</th><th>Score</th><th>%</th><th>Status</th><th>Submitted</th>${actions?'<th></th>':''}</tr></thead><tbody>${rows.map(r=>`<tr><td><b>${esc(r.student)}</b><small>${esc(r.email)}</small></td><td>${esc(r.exam)}</td><td>${r.score}/${r.total}</td><td>${pct(r)}%</td><td>${statusBadge(r.status)}</td><td>${esc(r.submitted)}</td>${actions?`<td><button class="btn btn-sm" data-action="result" data-id="${esc(r.id)}">Details</button></td>`:''}</tr>`).join('')}</tbody></table>`}
function exams(){return `<div class="page-card"><div class="section-title"><div><h2>Exam Portfolio</h2><span class="muted">${examSources.length} configured API source(s)</span></div><button class="btn btn-primary" data-action="new-source">＋ Add Exam Source</button></div><div class="exam-grid">${DATA.exams.map(e=>{const ratio=e.students?Math.min(100,e.submitted/e.students*100):100;return `<div class="exam-card"><div class="exam-head"><span class="code">${esc(e.code)}</span>${statusBadge(e.status)}</div><h3>${esc(e.name)}</h3><div class="exam-meta">${e.submitted} submissions • avg ${e.avg}%<br>${e.total} marks • pass at ${e.passing} • ${e.duration} min</div><div class="progress"><i style="width:${ratio}%"></i></div><div class="muted">Submission coverage ${ratio.toFixed(0)}%</div><div class="source-actions"><button class="btn btn-sm" data-action="select-exam" data-id="${esc(e.id)}">Open</button><button class="btn btn-sm" data-action="edit-source" data-id="${esc(e.id)}">Configure</button></div></div>`}).join('')||'<div class="empty">No live exams. Add an API source in Settings.</div>'}</div></div>`}
function results(){const rows=filteredResults();return `<div class="page-card"><div class="filter-head"><div><h2>Result Management</h2><span class="muted">${rows.length} matching result(s)</span></div><button class="btn" data-action="export-results">Export current view</button></div><div class="filters"><input class="field search" id="resultSearch" placeholder="Search student, roll, email, exam…" value="${esc(searchTerm)}"><select class="field" id="resultStatus"><option value="ALL">All statuses</option><option value="PASS" ${resultStatus==='PASS'?'selected':''}>PASS</option><option value="FAIL" ${resultStatus==='FAIL'?'selected':''}>FAIL</option></select></div>${resultTable(rows,true)}</div>`}
function students(){const rows=filteredStudents();return `<div class="page-card"><div class="filter-head"><div><h2>Student 360° Directory</h2><span class="muted">${rows.length} student profile(s)</span></div><button class="btn" data-action="export-students">Export students</button></div><div class="filters"><input class="field search" id="studentSearch" placeholder="Search name, roll, email, class…" value="${esc(studentSearch)}"></div><div class="student-grid">${rows.map(s=>{const avg=s.results.reduce((a,r)=>a+pct(r),0)/s.results.length;return `<div class="student-card"><div class="student-avatar">${esc((s.name||'?').charAt(0).toUpperCase())}</div><div class="student-main"><h3>${esc(s.name)}</h3><p>${esc(s.email)}</p><small>Roll ${esc(s.roll||'—')} • ${esc(s.className||'—')}</small></div><div class="student-score"><b>${avg.toFixed(1)}%</b><small>${s.attempts} attempt${s.attempts===1?'':'s'}</small></div><button class="btn btn-sm" data-action="student" data-email="${esc(s.email)}">View 360°</button></div>`}).join('')||'<div class="empty">No students found.</div>'}</div></div>`}
function analytics(){const rows=filteredResults(),q={};rows.forEach(r=>(r.questions||[]).forEach(x=>{const k=x.question||x.q||x.h||'Question';if(!q[k])q[k]={q:k,total:0,answered:0};q[k].total++;if(String(x.answer??x.v??'').trim())q[k].answered++}));const qs=Object.values(q),avg=rows.length?rows.reduce((a,r)=>a+pct(r),0)/rows.length:0,pass=rows.filter(r=>r.status==='PASS').length,fail=rows.filter(r=>r.status==='FAIL').length,passRate=rows.length?pass/rows.length*100:0,median=rows.length?[...rows].map(pct).sort((a,b)=>a-b)[Math.floor(rows.length/2)]:0;const dist=[['0–39',0],['40–59',0],['60–79',0],['80–100',0]];rows.forEach(r=>{const p=pct(r);if(p<40)dist[0][1]++;else if(p<60)dist[1][1]++;else if(p<80)dist[2][1]++;else dist[3][1]++});return `<div class="cards"><div class="card"><div class="metric-label">Submissions</div><div class="metric">${rows.length}</div></div><div class="card"><div class="metric-label">Average</div><div class="metric">${avg.toFixed(1)}%</div></div><div class="card"><div class="metric-label">Pass Rate</div><div class="metric">${passRate.toFixed(1)}%</div></div><div class="card"><div class="metric-label">Median</div><div class="metric">${Number(median).toFixed(1)}%</div></div></div><div class="grid2"><div class="page-card"><div class="section-title"><h2>Score Distribution</h2><span class="muted">Current exam filter</span></div>${dist.map(d=>`<div class="bar-row"><span>${d[0]}</span><div class="bar"><i style="width:${rows.length?d[1]/rows.length*100:0}%"></i></div><b>${d[1]}</b></div>`).join('')}<div class="notice">PASS: ${pass} • FAIL: ${fail}</div></div><div class="page-card"><div class="section-title"><h2>Question Response Analytics</h2><span class="muted">Answered / observed</span></div>${qs.slice(0,30).map((x,i)=>`<div class="question-stat"><b>${i+1}. ${esc(x.q)}</b><small>${x.answered}/${x.total} answered • ${x.total?((x.answered/x.total)*100).toFixed(1):'0.0'}% response rate</small><div class="mini-progress"><i style="width:${x.total?x.answered/x.total*100:0}%"></i></div></div>`).join('')||'<div class="empty">No question-level data is available from the selected Google Apps Script API.</div>'}</div></div>`}
function comparison(){const exams=DATA.exams;return `<div class="page-card"><div class="section-title"><div><h2>Exam Comparison</h2><span class="muted">Descriptive comparison across loaded sources</span></div><button class="btn" data-action="export-comparison">Export</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Exam</th><th>Code</th><th>Students</th><th>Submissions</th><th>Coverage</th><th>Average</th><th>Pass rate</th><th>Status</th></tr></thead><tbody>${exams.map(e=>{const r=DATA.results.filter(x=>String(x.examId)===String(e.id)),p=r.length?r.filter(x=>x.status==='PASS').length/r.length*100:0;return `<tr><td><b>${esc(e.name)}</b></td><td>${esc(e.code)}</td><td>${e.students}</td><td>${e.submitted}</td><td>${e.students?(e.submitted/e.students*100).toFixed(1):'100.0'}%</td><td>${e.avg}%</td><td>${p.toFixed(1)}%</td><td>${statusBadge(e.status)}</td></tr>`}).join('')||'<tr><td colspan="8">No exams.</td></tr>'}</tbody></table></div></div>`}
function reports(){return `<div class="grid2"><div class="page-card"><h2>Professional Exports</h2><p class="muted">Exports use the current global exam filter.</p><div class="report-actions"><button class="report-btn" data-action="export-xls">📊 Excel-compatible workbook</button><button class="report-btn" data-action="export-csv">▤ CSV results</button><button class="report-btn" data-action="export-json">◇ JSON backup</button><button class="report-btn" data-action="print-report">🖨 Print / PDF</button><button class="report-btn" data-action="certificate">🎓 Certificate template</button></div></div><div class="page-card"><h2>Archive Snapshot</h2><p class="muted">Create a local snapshot of the loaded dashboard data and settings.</p><button class="btn btn-primary" data-action="backup">Create backup</button><div class="notice">Backups stay in your browser unless you download them. For a shared audit trail, store reports in a controlled Drive location.</div></div></div>`}
function settings(){return `<div class="grid2"><div class="page-card"><div class="section-title"><div><h2>Exam API Sources</h2><span class="muted">One Apps Script /exec URL per Google Form response Sheet</span></div><button class="btn btn-primary" data-action="new-source">＋ Add</button></div>${examSources.map((s,i)=>`<div class="source-row"><div class="source-fields"><input class="field" data-src="name" data-i="${i}" value="${esc(s.name)}" placeholder="Exam name"><input class="field" data-src="code" data-i="${i}" value="${esc(s.code||'')}" placeholder="Code"><input class="field source-url" data-src="url" data-i="${i}" value="${esc(s.url)}" placeholder="Apps Script /exec URL"><label class="source-active"><input type="checkbox" data-src="active" data-i="${i}" ${s.active!==false?'checked':''}> Active</label></div><div class="source-actions"><select class="field compact" data-src="status" data-i="${i}"><option value="AUTO" ${!s.expectedStatus||s.expectedStatus==='AUTO'?'selected':''}>Status: Auto</option><option value="UPCOMING" ${s.expectedStatus==='UPCOMING'?'selected':''}>Upcoming</option><option value="LIVE" ${s.expectedStatus==='LIVE'?'selected':''}>Live</option><option value="COMPLETED" ${s.expectedStatus==='COMPLETED'?'selected':''}>Completed</option><option value="ARCHIVED" ${s.expectedStatus==='ARCHIVED'?'selected':''}>Archived</option></select><button class="btn btn-sm" data-action="test-source" data-i="${i}">Test</button><button class="btn btn-sm" data-action="edit-source" data-id="${esc(s.id)}">Save</button><button class="btn btn-sm danger" data-action="delete-source" data-i="${i}">Delete</button></div></div>`).join('')||'<div class="empty">No sources configured.</div>'}<button class="btn btn-primary" data-action="save-sources">Save all sources</button></div><div class="page-card"><h2>System Health & Audit</h2><div class="health-panel"><div><b>Mode</b><span>${LIVE_MODE?'LIVE':'DEMO'}</span></div><div><b>Sources</b><span>${examSources.length}</span></div><div><b>Last sync</b><span>${esc($('#lastUpdated')?.textContent||'—')}</span></div><div><b>Browser storage</b><span>${localStorage?'Available':'Unavailable'}</span></div></div><button class="btn" data-action="health-check">Run API health check</button><button class="btn" data-action="audit-view">View audit log</button><div class="notice">Security note: a public Apps Script JSON endpoint is readable by anyone who has its URL. Use Google access controls or a server-side gateway before exposing student data publicly.</div></div></div>`}
function openModal(html){
  const modal=$('#modal');
  modal.innerHTML=html;
  modal.onclick=(e)=>{
    const b=e.target.closest('[data-action]');
    if(!b || !modal.contains(b))return;
    const a=b.dataset.action;
    if(a==='close')return closeModal();
    if(a==='create-source')return createSource();
  };
  $('#modalBackdrop').classList.add('show');
}
function closeModal(){ $('#modalBackdrop').classList.remove('show'); }

function showResult(id){const r=DATA.results.find(x=>x.id===id);if(!r)return;openModal(`<div class="modal-head"><div><h2>${esc(r.student)}</h2><span class="muted">${esc(r.exam)}</span></div><button class="close" data-action="close">✕</button></div><div class="detail-grid"><div class="detail"><small>Score</small><b>${r.score}/${r.total} (${pct(r)}%)</b></div><div class="detail"><small>Status</small><b>${statusBadge(r.status)}</b></div><div class="detail"><small>Submitted</small><b>${esc(r.submitted)}</b></div><div class="detail"><small>Roll</small><b>${esc(r.roll||'—')}</b></div><div class="detail"><small>Email</small><b>${esc(r.email||'—')}</b></div><div class="detail"><small>Mobile</small><b>${esc(r.mobile||'—')}</b></div></div><h3>Submitted Answers</h3>${r.questions?.length?r.questions.map((q,i)=>`<div class="question"><b>Q${q.number||i+1}. ${esc(q.question||q.q||q.h)}</b><br><span>${esc(q.answer??q.v??'')}</span></div>`).join(''):'<div class="empty">No question-level answers returned by this API.</div>'}`)}
function showStudent(email){const rows=DATA.results.filter(r=>r.email===email);const s=studentsFrom(rows)[0];if(!s)return;const avg=rows.reduce((a,r)=>a+pct(r),0)/rows.length;openModal(`<div class="modal-head"><div><h2>${esc(s.name)}</h2><span class="muted">Student 360° profile</span></div><button class="close" data-action="close">✕</button></div><div class="detail-grid"><div class="detail"><small>Email</small><b>${esc(s.email)}</b></div><div class="detail"><small>Roll</small><b>${esc(s.roll||'—')}</b></div><div class="detail"><small>Average</small><b>${avg.toFixed(1)}%</b></div></div><h3>Exam History</h3>${rows.map(r=>`<div class="history-row"><div><b>${esc(r.exam)}</b><small>${esc(r.submitted)}</small></div><strong>${r.score}/${r.total} • ${pct(r)}% ${statusBadge(r.status)}</strong></div>`).join('')}`)}
function newSource(){openModal(`<div class="modal-head"><div><h2>Add New Examination</h2><span class="muted">Connect one Google Apps Script /exec API for this exam.</span></div><button class="close" data-action="close">✕</button></div><div class="form-grid"><label>Exam Name<input class="field" id="newExamName" value="" placeholder="Computer Science Assessment"></label><label>Exam Code<input class="field" id="newExamCode" value="" placeholder="CSA-2026"></label><label class="wide">Apps Script Web App URL<input class="field" id="newExamUrl" placeholder="https://script.google.com/macros/s/.../exec"></label><label>Status<select class="field" id="newExamStatus"><option value="AUTO">Auto</option><option value="UPCOMING">Upcoming</option><option value="LIVE">Live</option><option value="COMPLETED">Completed</option><option value="ARCHIVED">Archived</option></select></label></div><div class="modal-actions"><button class="btn" data-action="close">Cancel</button><button class="btn btn-primary" data-action="create-source">Add Examination</button></div>`);}
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function currentRows(){return filteredResults()}
function exportCSV(){const rows=currentRows();const head=['Exam','Student','Roll','Email','Mobile','Class','Score','Total','Percentage','Status','Submitted'];const lines=[head,...rows.map(r=>[r.exam,r.student,r.roll,r.email,r.mobile,r.classDepartment,r.score,r.total,pct(r),r.status,r.submitted])].map(a=>a.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(','));download('exam-results.csv',lines.join('\n'),'text/csv;charset=utf-8');audit('EXPORT_CSV',`${rows.length} rows`)}
function exportXLS(){const rows=currentRows(),ex=filteredExams();let h='<html><head><meta charset="UTF-8"></head><body>';const table=(title,heads,data)=>{h+=`<h2>${esc(title)}</h2><table border="1"><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>${data.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</table>`};table('Results',['Exam','Student','Roll','Email','Mobile','Class','Score','Total','Percentage','Status','Submitted'],rows.map(r=>[r.exam,r.student,r.roll,r.email,r.mobile,r.classDepartment,r.score,r.total,pct(r),r.status,r.submitted]));table('Exam Overview',['Exam','Code','Students','Submissions','Average','Total Marks','Passing Marks','Status'],ex.map(e=>[e.name,e.code,e.students,e.submitted,e.avg,e.total,e.passing,e.status]));const ss=studentsFrom(rows);table('Students',['Name','Roll','Email','Class','Attempts','Average'],ss.map(s=>[s.name,s.roll,s.email,s.className,s.attempts,(s.results.reduce((a,r)=>a+pct(r),0)/s.results.length).toFixed(1)]));h+='</body></html>';download('exam-report.xls',h,'application/vnd.ms-excel');audit('EXPORT_EXCEL',`${rows.length} results`)}
function exportJSON(){download('exam-dashboard-backup.json',JSON.stringify({exportedAt:new Date().toISOString(),sources:examSources,data:DATA},null,2),'application/json');audit('EXPORT_JSON')}
function printReport(){const rows=currentRows(),w=window.open('','_blank');w.document.write(`<html><head><title>Exam Report</title><style>body{font:12px Arial;padding:25px}table{width:100%;border-collapse:collapse}th,td{border:1px solid #bbb;padding:7px;text-align:left}h1{margin-bottom:4px}</style></head><body><h1>Examination Report</h1><p>Generated ${new Date().toLocaleString()}</p>${resultTable(rows,false)}</body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),300);audit('PRINT_REPORT',`${rows.length} rows`)}
function certificate(){const r=currentRows()[0];if(!r){alert('Select an exam/result first.');return}const w=window.open('','_blank');w.document.write(`<html><head><title>Certificate</title><style>body{font-family:Georgia;text-align:center;padding:80px;border:15px solid #1e3a66;margin:25px}h1{font-size:42px}h2{font-size:30px}p{font-size:18px}</style></head><body><h1>Certificate of Achievement</h1><p>This certifies that</p><h2>${esc(r.student)}</h2><p>has completed <b>${esc(r.exam)}</b></p><p>Score: <b>${r.score}/${r.total} (${pct(r)}%)</b></p><p>${esc(r.submitted)}</p><script>window.print()<\/script></body></html>`);w.document.close();audit('CERTIFICATE',r.student)}
function backup(){exportJSON()}
function createSource(){const name=($('#newExamName')?.value||'').trim(),code=($('#newExamCode')?.value||'').trim(),url=($('#newExamUrl')?.value||'').trim(),status=$('#newExamStatus')?.value||'AUTO';if(!name||!url){alert('Please enter Exam Name and the Apps Script /exec URL.');return}if(!/^https?:\/\//i.test(url)){alert('Enter a valid HTTPS Apps Script /exec URL.');return}const id='EXAM-'+Date.now();examSources.push({id,name,code:code||id,url,active:true,expectedStatus:status});saveSources();audit('ADD_SOURCE',`${name} (${id})`);closeModal();selectedExamId='ALL';loadAllLiveData().catch(e=>{render();alert('Exam added, but API sync failed.\n\n'+e.message)});}
function healthCheck(){if(!examSources.length){alert('No sources configured.');return}Promise.all(examSources.map(async s=>{const t=Date.now();try{await fetchSource(s);return `${s.name}: OK (${Date.now()-t} ms)`}catch(e){return `${s.name}: ERROR — ${e.message}`} })).then(a=>openModal(`<div class="modal-head"><h2>API Health Check</h2><button class="close" data-action="close">✕</button></div>${a.map(x=>`<div class="health-result">${esc(x)}</div>`).join('')}`))}
function auditView(){let a=[];try{a=JSON.parse(localStorage.getItem('auditLog')||'[]')}catch(e){}openModal(`<div class="modal-head"><h2>Audit Log</h2><button class="close" data-action="close">✕</button></div>${a.slice(0,50).map(x=>`<div class="history-row"><div><b>${esc(x.action)}</b><small>${esc(x.detail)}</small></div><span>${new Date(x.time).toLocaleString()}</span></div>`).join('')||'<div class="empty">No actions recorded.</div>'}`)}
function bindPage(){
 $('#resultSearch')?.addEventListener('input',e=>{searchTerm=e.target.value;render()});$('#resultStatus')?.addEventListener('change',e=>{resultStatus=e.target.value;render()});$('#studentSearch')?.addEventListener('input',e=>{studentSearch=e.target.value;render()});
 $$('[data-src]').forEach(el=>el.addEventListener('change',e=>{const i=Number(el.dataset.i),k=el.dataset.src;if(k==='status')examSources[i].expectedStatus=el.value;else examSources[i][k]=el.type==='checkbox'?el.checked:el.value}));
 $$('[data-action]').forEach(b=>b.addEventListener('click',()=>{const a=b.dataset.action;if(a==='close')return closeModal();if(a==='go-results'){currentPage='results';return render()}if(a==='go-students'){currentPage='students';return render()}if(a==='go-analytics'){currentPage='analytics';return render()}if(a==='go-reports'){currentPage='reports';return render()}if(a==='go-settings'){currentPage='settings';return render()}if(a==='result')return showResult(b.dataset.id);if(a==='student')return showStudent(b.dataset.email);if(a==='new-source')return newSource();if(a==='create-source')return createSource();if(a==='delete-source'){examSources.splice(Number(b.dataset.i),1);saveSources();audit('DELETE_SOURCE');render();return}if(a==='save-sources'||a==='edit-source'){saveSources();audit('SAVE_SOURCES');render();return}if(a==='test-source'){const s=examSources[Number(b.dataset.i)];if(!s.url)return alert('Enter the Apps Script /exec URL first.');b.disabled=true;fetchSource(s).then(x=>alert(`${s.name}\nAPI OK\n${x.results.length} results loaded`)).catch(e=>alert(`${s.name}\nAPI ERROR\n${e.message}`)).finally(()=>b.disabled=false);return}if(a==='select-exam'){selectedExamId=b.dataset.id;localStorage.setItem('selectedExamId',selectedExamId);currentPage='dashboard';render();return}if(a==='export-results'){exportCSV();return}if(a==='export-students'){const rows=filteredStudents();download('students.csv',['Name,Roll,Email,Class,Attempts',...rows.map(s=>[s.name,s.roll,s.email,s.className,s.attempts].map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(','))].join('\n'),'text/csv');return}if(a==='export-xls')return exportXLS();if(a==='export-csv')return exportCSV();if(a==='export-json')return exportJSON();if(a==='print-report')return printReport();if(a==='certificate')return certificate();if(a==='backup')return backup();if(a==='health-check')return healthCheck();if(a==='audit-view')return auditView();if(a==='export-comparison')return exportXLS() }));
}
$$('.nav-item').forEach(b=>b.addEventListener('click',()=>{currentPage=b.dataset.page;$('#sidebar').classList.remove('open');render()}));
$('#refreshBtn').addEventListener('click',refreshData);
$('#menuBtn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$('#globalExamFilter').addEventListener('change',e=>{selectedExamId=e.target.value;localStorage.setItem('selectedExamId',selectedExamId);render()});
$('#modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal()});
document.addEventListener('keydown',e=>{if(e.key==='Escape' && $('#modalBackdrop').classList.contains('show'))closeModal();});

setInterval(()=>{if(examSources.length&&!API_LOADING)loadAllLiveData(true).catch(()=>{});},5*60*1000);
render();
